//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryClient.WeixinServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://anjismart.com/", ConfigurationName="WeixinServiceReference.WeixinServiceSoap")]
    public interface WeixinServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://anjismart.com/TestConn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TestConn(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://anjismart.com/TestConn", ReplyAction="*")]
        System.Threading.Tasks.Task<string> TestConnAsync(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://anjismart.com/Query", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Query(string code, string feature);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://anjismart.com/Query", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryAsync(string code, string feature);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WeixinServiceSoapChannel : QueryClient.WeixinServiceReference.WeixinServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeixinServiceSoapClient : System.ServiceModel.ClientBase<QueryClient.WeixinServiceReference.WeixinServiceSoap>, QueryClient.WeixinServiceReference.WeixinServiceSoap {
        
        public WeixinServiceSoapClient() {
        }
        
        public WeixinServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeixinServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeixinServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeixinServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TestConn(string text) {
            return base.Channel.TestConn(text);
        }
        
        public System.Threading.Tasks.Task<string> TestConnAsync(string text) {
            return base.Channel.TestConnAsync(text);
        }
        
        public string Query(string code, string feature) {
            return base.Channel.Query(code, feature);
        }
        
        public System.Threading.Tasks.Task<string> QueryAsync(string code, string feature) {
            return base.Channel.QueryAsync(code, feature);
        }
    }
}
