//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryClient.PhoneServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PhoneServiceReference.IPhoneService")]
    public interface IPhoneService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneService/Query", ReplyAction="http://tempuri.org/IPhoneService/QueryResponse")]
        string Query(string code, string phoneNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhoneService/Query", ReplyAction="http://tempuri.org/IPhoneService/QueryResponse")]
        System.Threading.Tasks.Task<string> QueryAsync(string code, string phoneNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhoneServiceChannel : QueryClient.PhoneServiceReference.IPhoneService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhoneServiceClient : System.ServiceModel.ClientBase<QueryClient.PhoneServiceReference.IPhoneService>, QueryClient.PhoneServiceReference.IPhoneService {
        
        public PhoneServiceClient() {
        }
        
        public PhoneServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhoneServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Query(string code, string phoneNumber) {
            return base.Channel.Query(code, phoneNumber);
        }
        
        public System.Threading.Tasks.Task<string> QueryAsync(string code, string phoneNumber) {
            return base.Channel.QueryAsync(code, phoneNumber);
        }
    }
}
